name: CI

on:
  push:
    branches:
      - master
      - fix
  pull_request:
    branches:
      - '*'

jobs:
  graal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup GraalVM CE
        uses: rinx/setup-graalvm-ce@v0.0.5
        with:
          graalvm-version: "21.0.0.2"
          java-version: "java8"
          native-image: "true"

      - name: Cache Gradle wrapper and dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/dists
          key: test-${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/*.gradle.kts', '**/gradle.properties', 'gradle/**', 'buildSrc/src/main/**') }}
          restore-keys: |
            test-${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: ./gradlew nativeImage

      - name: Save app
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: |
            build/native-image/application

      - name: Run app for testing
        run: |
          nohup ./build/native-image/application &
          sleep 5s
